### ISSUE TITLE
Remove 3Rnd UGL mags

### ISSUE THREAD

**Issue by Delta1292** [Sniperhid/1Tac-F3#10]
Remove the 3Rnd UGL mags as standard from f_assignGear_nato

Specifically:
Lines 129 -> 132
Change from
_glflarewhite = "3Rnd_UGL_FlareWhite_F";
_glflarered = "3Rnd_UGL_FlareRed_F";
_glflareyellow = "3Rnd_UGL_FlareYellow_F";
_glflaregreen = "3Rnd_UGL_FlareGreen_F";

To
_glflarewhite = "UGL_FlareWhite_F";
_glflarered = "UGL_FlareRed_F";
_glflareyellow = "UGL_FlareYellow_F";
_glflaregreen = "UGL_FlareGreen_F";

This will retain compatibility with 1Tacmags which has removed the ability to use 3 round UGL mags in all M4 variants (RH+RHS)

**Comment by Sniperhid** [comment]
Fixed by Nick
