### ISSUE TITLE
No Fixed wing Group Markers

### ISSUE THREAD

**Issue by Delta1292** [Sniperhid/1Tac-F3#16]

**Comment by beaar** [comment]
\f3_groupmarkers\textures\red_fixedwing.paa
![red_fixedwing](https://cloud.githubusercontent.com/assets/9511798/8610561/dfec3498-26b3-11e5-9dd6-9aa8ffa277fe.png)

blue, yellow, green, orange variants exist

**Comment by Sniperhid** [comment]
Yeah in future check f3_groupmarkers.pbo for all the images!
