### ISSUE TITLE
Explore disabling elements of HUD

### ISSUE THREAD

**Issue by Sniperhid** [Sniperhid/1Tac-F3#20]
Suggest hiding command bar from leaders in groups in which all units in the group are players?
https://community.bistudio.com/wiki/showHUD

**Comment by NickvdLee** [comment]
ACE3 looked into it, impossible.

**Comment by NickvdLee** [comment]
Aaaaand I forgot about that command, should not arma while at work

**Comment by Sniperhid** [comment]
already done
